// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfh3lIWA2lGYG9YosEGF120C2s1_XNtkg',
    appId: '1:901776408095:web:444117b9897afc473d5f2a',
    messagingSenderId: '901776408095',
    projectId: 'ahorra-budget-companion',
    authDomain: 'ahorra-budget-companion.firebaseapp.com',
    storageBucket: 'ahorra-budget-companion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE68W7FL8vbxQEL78IQnFltqH7LFIwJRk',
    appId: '1:901776408095:android:c0d088e14c773c2c3d5f2a',
    messagingSenderId: '901776408095',
    projectId: 'ahorra-budget-companion',
    storageBucket: 'ahorra-budget-companion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhAxY1eZ_o2ou50Y4esDNoL7ygmPHv6Es',
    appId: '1:901776408095:ios:a8766a3ab6394fd83d5f2a',
    messagingSenderId: '901776408095',
    projectId: 'ahorra-budget-companion',
    storageBucket: 'ahorra-budget-companion.firebasestorage.app',
    iosBundleId: 'com.example.ahorra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhAxY1eZ_o2ou50Y4esDNoL7ygmPHv6Es',
    appId: '1:901776408095:ios:a8766a3ab6394fd83d5f2a',
    messagingSenderId: '901776408095',
    projectId: 'ahorra-budget-companion',
    storageBucket: 'ahorra-budget-companion.firebasestorage.app',
    iosBundleId: 'com.example.ahorra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfh3lIWA2lGYG9YosEGF120C2s1_XNtkg',
    appId: '1:901776408095:web:25615684dedba8933d5f2a',
    messagingSenderId: '901776408095',
    projectId: 'ahorra-budget-companion',
    authDomain: 'ahorra-budget-companion.firebaseapp.com',
    storageBucket: 'ahorra-budget-companion.firebasestorage.app',
  );
}
